"""followers corrected

Revision ID: 5fef6fff61fa
Revises: 03102364f39f
Create Date: 2018-06-27 15:22:06.578141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fef6fff61fa'
down_revision = '03102364f39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
